//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.GeneralTimes = new HashSet<GeneralTime>();
            this.NotificationVendors = new HashSet<NotificationVendor>();
            this.PushTimeTickets = new HashSet<PushTimeTicket>();
            this.Territories = new HashSet<Territory>();
            this.TimeTickets = new HashSet<TimeTicket>();
            this.Trucks = new HashSet<Truck>();
            this.Users = new HashSet<User>();
            this.VendorEquipments = new HashSet<VendorEquipment>();
            this.VendorEquipments1 = new HashSet<VendorEquipment>();
            this.VendorFeeRates = new HashSet<VendorFeeRate>();
            this.VendorForemen = new HashSet<VendorForeman>();
            this.VendorForemen1 = new HashSet<VendorForeman>();
            this.VendorProperties = new HashSet<VendorProperty>();
            this.VendorRoutes = new HashSet<VendorRoute>();
            this.VendorRoutes1 = new HashSet<VendorRoute>();
            this.VendorWorkers = new HashSet<VendorWorker>();
            this.VendorWorkTypes = new HashSet<VendorWorkType>();
            this.WeatherEvents = new HashSet<WeatherEvent>();
            this.WorkEvents = new HashSet<WorkEvent>();
        }
    
        public int VendorId { get; set; }
        public string BusinessName { get; set; }
        public string CheckName { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string ZipCode { get; set; }
        public string AttentionName { get; set; }
        public string EinSsn { get; set; }
        public bool IsContactSheetOnfile { get; set; }
        public bool IsInsuranceOnFile { get; set; }
        public bool IsWce1OnFile { get; set; }
        public bool IsActive { get; set; }
        public bool IsObsolete { get; set; }
        public bool Is1099 { get; set; }
        public bool IsForeman { get; set; }
        public bool IsOutlying { get; set; }
        public bool IsFuelSurcharge { get; set; }
        public Nullable<System.DateTime> InsuranceExpirationDate { get; set; }
        public Nullable<System.DateTime> Wce1ExpirationDate { get; set; }
        public string ContactName { get; set; }
        public string HomePhoneNumber { get; set; }
        public string WorkPhoneNumber { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string EmergencyPhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string AlternateContactName { get; set; }
        public string AlternateContactPhoneNumber { get; set; }
        public string Trade { get; set; }
        public string QbReference { get; set; }
        public string Comments { get; set; }
        public bool IsSyncNeeded { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string ABList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralTime> GeneralTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationVendor> NotificationVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PushTimeTicket> PushTimeTickets { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Territory> Territories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTicket> TimeTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Truck> Trucks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorEquipment> VendorEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorEquipment> VendorEquipments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorFeeRate> VendorFeeRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorForeman> VendorForemen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorForeman> VendorForemen1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorProperty> VendorProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorRoute> VendorRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorRoute> VendorRoutes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorWorker> VendorWorkers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorWorkType> VendorWorkTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeatherEvent> WeatherEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkEvent> WorkEvents { get; set; }
    }
}
