//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaskTrip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalAddress
    {
        public int ProposalAddressId { get; set; }
        public int ProposalId { get; set; }
        public int ProposalAddressTypeId { get; set; }
        public Nullable<int> CompanyAddressId { get; set; }
        public Nullable<int> PropertyAddressId { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string ZipCode { get; set; }
        public string Attention { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual CompanyAddress CompanyAddress { get; set; }
        public virtual PropertyAddress PropertyAddress { get; set; }
        public virtual Proposal Proposal { get; set; }
        public virtual ProposalAddressType ProposalAddressType { get; set; }
        public virtual State State { get; set; }
    }
}
