//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyContract()
        {
            this.PropertyFeeRates = new HashSet<PropertyFeeRate>();
            this.PropertyFlatRates = new HashSet<PropertyFlatRate>();
        }
    
        public int PropertyContractId { get; set; }
        public int PropertyId { get; set; }
        public bool IsSignatureRequired { get; set; }
        public bool IsFuelSurcharge { get; set; }
        public bool IsFinanceCharge { get; set; }
        public bool IsCreditCardFee { get; set; }
        public bool IsThirdParty { get; set; }
        public Nullable<int> PaymentTermId { get; set; }
        public string PoNumber { get; set; }
        public bool IsProposal { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsVerbal { get; set; }
    
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual Property Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyFeeRate> PropertyFeeRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyFlatRate> PropertyFlatRates { get; set; }
    }
}
