//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaskTrip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.CompanyProperties = new HashSet<CompanyProperty>();
            this.Jobs = new HashSet<Job>();
            this.PropertyAddresses = new HashSet<PropertyAddress>();
            this.PropertyContacts = new HashSet<PropertyContact>();
            this.PropertyContracts = new HashSet<PropertyContract>();
            this.PropertyDocuments = new HashSet<PropertyDocument>();
            this.PropertyInvoiceDeliveries = new HashSet<PropertyInvoiceDelivery>();
            this.PropertyWorkTypes = new HashSet<PropertyWorkType>();
            this.Proposals = new HashSet<Proposal>();
            this.VendorProperties = new HashSet<VendorProperty>();
        }
    
        public int PropertyId { get; set; }
        public string PropertyName { get; set; }
        public string Landmark { get; set; }
        public string OnsiteManager { get; set; }
        public string OnsitePhone { get; set; }
        public Nullable<int> TerritoryId { get; set; }
        public Nullable<double> LotSizeAcres { get; set; }
        public Nullable<double> SidewalkInHours { get; set; }
        public Nullable<int> SidewalkSqFt { get; set; }
        public Nullable<double> PlowtimeInHours { get; set; }
        public Nullable<double> IcemeltBags { get; set; }
        public string SalesRep { get; set; }
        public string BillingEmailAddress { get; set; }
        public string QbJob { get; set; }
        public string QbReference { get; set; }
        public string Comments { get; set; }
        public bool IsActiveContract { get; set; }
        public bool IsSyncNeeded { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string HoursOfOperation { get; set; }
        public string SitefotosUrl { get; set; }
        public bool Open24Hours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyProperty> CompanyProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual Territory Territory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyAddress> PropertyAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContact> PropertyContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContract> PropertyContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyDocument> PropertyDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyInvoiceDelivery> PropertyInvoiceDeliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyWorkType> PropertyWorkTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposal> Proposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorProperty> VendorProperties { get; set; }
    }
}
