//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushTimeTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PushTimeTicket()
        {
            this.PushTimeTicketProperties = new HashSet<PushTimeTicketProperty>();
        }
    
        public long PushTimeTicketId { get; set; }
        public long WorkEventId { get; set; }
        public Nullable<int> TimeTicketId { get; set; }
        public int VendorId { get; set; }
        public int EquipmentId { get; set; }
        public string ReferenceNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual TimeTicket TimeTicket { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual WorkEvent WorkEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PushTimeTicketProperty> PushTimeTicketProperties { get; set; }
    }
}
