//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaskTrip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTicketProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTicketProperty()
        {
            this.PushTimeTicketProperties = new HashSet<PushTimeTicketProperty>();
        }
    
        public int TimeTicketPropertyId { get; set; }
        public int TimeTicketId { get; set; }
        public int VendorPropertyId { get; set; }
        public Nullable<int> StopOrder { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PushTimeTicketProperty> PushTimeTicketProperties { get; set; }
        public virtual TimeTicket TimeTicket { get; set; }
        public virtual VendorProperty VendorProperty { get; set; }
    }
}
