//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTicket()
        {
            this.PushTimeTickets = new HashSet<PushTimeTicket>();
            this.TimeTicketProperties = new HashSet<TimeTicketProperty>();
        }
    
        public int TimeTicketId { get; set; }
        public int VendorRouteId { get; set; }
        public int VendorId { get; set; }
        public int SeasonId { get; set; }
        public int Number { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PushTimeTicket> PushTimeTickets { get; set; }
        public virtual Season Season { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual VendorRoute VendorRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTicketProperty> TimeTicketProperties { get; set; }
    }
}
