//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwForemanAlia
    {
        public int TerritoryId { get; set; }
        public string Territory { get; set; }
        public Nullable<int> AliasForemanId { get; set; }
        public Nullable<bool> AliasIsForeman { get; set; }
        public Nullable<bool> AliasIsActive { get; set; }
        public int ActualForemanId { get; set; }
        public string ActualBusinessName { get; set; }
        public string ActualForemanName { get; set; }
        public bool ActualIsForeman { get; set; }
        public int ActualIsActive { get; set; }
        public string IsOutlying { get; set; }
    }
}
