//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeatherEvent()
        {
            this.Trips = new HashSet<Trip>();
            this.TripRoutes = new HashSet<TripRoute>();
            this.WeatherEventPrecipitations = new HashSet<WeatherEventPrecipitation>();
            this.WeatherEventSurfaces = new HashSet<WeatherEventSurface>();
            this.WorkEvents = new HashSet<WorkEvent>();
        }
    
        public int WeatherEventId { get; set; }
        public int SeasonId { get; set; }
        public int VendorId { get; set; }
        public string Name { get; set; }
        public int Temperature { get; set; }
        public int AccumulationTypeId { get; set; }
        public int WindTypeId { get; set; }
        public bool IsDrifting { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> TerritoryId { get; set; }
    
        public virtual AccumulationType AccumulationType { get; set; }
        public virtual Season Season { get; set; }
        public virtual Territory Territory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trip> Trips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripRoute> TripRoutes { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual WindType WindType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeatherEventPrecipitation> WeatherEventPrecipitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeatherEventSurface> WeatherEventSurfaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkEvent> WorkEvents { get; set; }
    }
}
