//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaskTrip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherEventPrecipitation
    {
        public int WeatherEventPrecipitationId { get; set; }
        public int WeatherEventId { get; set; }
        public int PrecipitationTypeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual PrecipitationType PrecipitationType { get; set; }
        public virtual WeatherEvent WeatherEvent { get; set; }
    }
}
