//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trip.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkEvent()
        {
            this.GeneralTimes = new HashSet<GeneralTime>();
            this.Jobs = new HashSet<Job>();
            this.LotSaltTimes = new HashSet<LotSaltTime>();
            this.PushTimeTickets = new HashSet<PushTimeTicket>();
            this.SidewalkTimes = new HashSet<SidewalkTime>();
        }
    
        public long WorkEventId { get; set; }
        public int VendorId { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public int WorkTypeId { get; set; }
        public Nullable<int> WeatherEventId { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralTime> GeneralTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LotSaltTime> LotSaltTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PushTimeTicket> PushTimeTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SidewalkTime> SidewalkTimes { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual WeatherEvent WeatherEvent { get; set; }
        public virtual WorkType WorkType { get; set; }
    }
}
